### ISSUE TITLE
NativeAOT

### ISSUE THREAD

**Issue by fxgenstudio** [gamedevcb/neonshooter_nativeAOT#1]
Thanks for your sample, I have a problem with package version ..

C:\Users\jnada\Downloads\neonshooter_nativeAOT-main\MyGame\MyGame.csproj : error NU1102: Package runtime.win-x64.Microsoft.DotNet.ILCompiler avec la version (>= 6.0.0-preview.3.21153.3) introuvable [C:\Users\jnada\Downloads\neonshooter_nativeAOT-main\MyGame.sln]
C:\Users\jnada\Downloads\neonshooter_nativeAOT-main\MyGame\MyGame.csproj : error NU1102:   - Version(s) 642 trouvée(s) dans dotnet-core [version la plus proche : 1.0.0-alpha-29408-02] [C:\Users\jnada\Downloads\neonshooter_nativeAOT-main\MyGame.sln]
C:\Users\jnada\Downloads\neonshooter_nativeAOT-main\MyGame\MyGame.csproj : error NU1102:   - Version(s) 0 trouvée(s) dans nuget.org [C:\Users\jnada\Downloads\neonshooter_nativeAOT-main\MyGame.sln]
  Échec de la restauration de C:\Users\jnada\Downloads\neonshooter_nativeAOT-main\MyGame\MyGame.csproj (en 998 ms).

**Comment by procfxgen** [comment]
Under command prompt ...

C:\Users\jnada\Downloads\neonshooter_nativeAOT-main\MyGame\MyGame.csproj : error NU1102: Package runtime.win-x64.Microsoft.DotNet.ILCompiler avec la version (>= 6.0.0-preview.3.21153.3) introuvable [C:\Users\jnada\Downloads\neonshooter_nativeAOT-main\MyGame.sln]
C:\Users\jnada\Downloads\neonshooter_nativeAOT-main\MyGame\MyGame.csproj : error NU1102:   - Version(s) 642 trouvée(s) dans dotnet-core [version la plus proche : 1.0.0-alpha-29408-02] [C:\Users\jnada\Downloads\neonshooter_nativeAOT-main\MyGame.sln]
C:\Users\jnada\Downloads\neonshooter_nativeAOT-main\MyGame\MyGame.csproj : error NU1102:   - Version(s) 0 trouvée(s) dans nuget.org [C:\Users\jnada\Downloads\neonshooter_nativeAOT-main\MyGame.sln]
  Échec de la restauration de C:\Users\jnada\Downloads\neonshooter_nativeAOT-main\MyGame\MyGame.csproj (en 998 ms).

**Comment by kant2002** [comment]
@procfxgen when working with NativeAOT, don't forget to include this Nuget feed in your nuget.config

https://github.com/dotnet/runtimelab/blob/4bfcec8c77a13f73fec3df1541f41720193f59e2/samples/HelloWorld/nuget.config#L7

**Comment by fxgenstudio** [comment]
Thank that work now !
